-- MySQL Script generated by MySQL Workbench
-- Tue Jan 12 19:45:50 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema dh_biogarden
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dh_biogarden` ;

-- -----------------------------------------------------
-- Schema dh_biogarden
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dh_biogarden` DEFAULT CHARACTER SET utf8 ;
USE `dh_biogarden` ;

-- -----------------------------------------------------
-- Table `dh_biogarden`.`users_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dh_biogarden`.`users_categories` ;

CREATE TABLE IF NOT EXISTS `dh_biogarden`.`users_categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)



-- -----------------------------------------------------
-- Table `dh_biogarden`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dh_biogarden`.`users` ;

CREATE TABLE IF NOT EXISTS `dh_biogarden`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(20) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `category_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `category_id` (`category_id` ASC) VISIBLE,
  CONSTRAINT `users_category_id_fk`
    FOREIGN KEY (`category_id`)
    REFERENCES `dh_biogarden`.`users_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)



-- -----------------------------------------------------
-- Table `dh_biogarden`.`payment_methods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dh_biogarden`.`payment_methods` ;

CREATE TABLE IF NOT EXISTS `dh_biogarden`.`payment_methods` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)



-- -----------------------------------------------------
-- Table `dh_biogarden`.`shipping_addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dh_biogarden`.`shipping_addresses` ;

CREATE TABLE IF NOT EXISTS `dh_biogarden`.`shipping_addresses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `street_name` VARCHAR(30) NOT NULL,
  `street_number` VARCHAR(10) NOT NULL,
  `city` VARCHAR(20) NOT NULL,
  `state` INT UNSIGNED NOT NULL,
  `zip_code` CHAR(4) NOT NULL,
  `other_info` VARCHAR(30) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)



-- -----------------------------------------------------
-- Table `dh_biogarden`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dh_biogarden`.`orders` ;

CREATE TABLE IF NOT EXISTS `dh_biogarden`.`orders` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `date_created` TIMESTAMP(3) NOT NULL,
  `total_amount` DECIMAL(5,2) UNSIGNED NOT NULL,
  `payment_method_id` INT UNSIGNED NOT NULL,
  `shipping_address_id` INT UNSIGNED NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) INVISIBLE,
  INDEX `method_payment_id` (`payment_method_id` ASC) INVISIBLE,
  INDEX `shipping_address_id` (`shipping_address_id` ASC) VISIBLE,
  CONSTRAINT `orders_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `dh_biogarden`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `orders_payment_method_id_fk`
    FOREIGN KEY (`payment_method_id`)
    REFERENCES `dh_biogarden`.`payment_methods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `orders_shipping_address_id_fk`
    FOREIGN KEY (`shipping_address_id`)
    REFERENCES `dh_biogarden`.`shipping_addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)



-- -----------------------------------------------------
-- Table `dh_biogarden`.`products_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dh_biogarden`.`products_categories` ;

CREATE TABLE IF NOT EXISTS `dh_biogarden`.`products_categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)



-- -----------------------------------------------------
-- Table `dh_biogarden`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dh_biogarden`.`products` ;

CREATE TABLE IF NOT EXISTS `dh_biogarden`.`products` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(30) NOT NULL,
  `price` DECIMAL(5,2) UNSIGNED NOT NULL,
  `image` VARCHAR(20) NOT NULL,
  `description` TEXT NOT NULL,
  `category_id` INT UNSIGNED NOT NULL,
  `quantity` INT ZEROFILL NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `category_id` (`category_id` ASC) VISIBLE,
  CONSTRAINT `products_product_category_id_fk`
    FOREIGN KEY (`category_id`)
    REFERENCES `dh_biogarden`.`products_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)



-- -----------------------------------------------------
-- Table `dh_biogarden`.`orders_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dh_biogarden`.`orders_detail` ;

CREATE TABLE IF NOT EXISTS `dh_biogarden`.`orders_detail` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  `amount` DECIMAL(5,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `orders_detail_order_id_fk` (`order_id` ASC) VISIBLE,
  INDEX `orders_detail_product_id_fk` (`product_id` ASC) VISIBLE,
  CONSTRAINT `orders_detail_order_id_fk`
    FOREIGN KEY (`order_id`)
    REFERENCES `dh_biogarden`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `orders_detail_product_id_fk`
    FOREIGN KEY (`product_id`)
    REFERENCES `dh_biogarden`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)



-- -----------------------------------------------------
-- Table `dh_biogarden`.`permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dh_biogarden`.`permissions` ;

CREATE TABLE IF NOT EXISTS `dh_biogarden`.`permissions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)



-- -----------------------------------------------------
-- Table `dh_biogarden`.`users_categories_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dh_biogarden`.`users_categories_permissions` ;

CREATE TABLE IF NOT EXISTS `dh_biogarden`.`users_categories_permissions` (
  `permission_id` INT UNSIGNED NOT NULL,
  `user_category_id` INT UNSIGNED NOT NULL,
  INDEX `permission_id` (`permission_id` ASC) INVISIBLE,
  INDEX `user_category_id` (`user_category_id` ASC) VISIBLE,
  CONSTRAINT `users_categories_permissions_permission_id_fk`
    FOREIGN KEY (`permission_id`)
    REFERENCES `dh_biogarden`.`permissions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `users_categories_permissions_user_category_id_fk`
    FOREIGN KEY (`user_category_id`)
    REFERENCES `dh_biogarden`.`users_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)



-- -----------------------------------------------------
-- Table `dh_biogarden`.`colours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dh_biogarden`.`colours` ;

CREATE TABLE IF NOT EXISTS `dh_biogarden`.`colours` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `hexadecimal` CHAR(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `hexadecimal_UNIQUE` (`hexadecimal` ASC) VISIBLE)



-- -----------------------------------------------------
-- Table `dh_biogarden`.`products_colours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dh_biogarden`.`products_colours` ;

CREATE TABLE IF NOT EXISTS `dh_biogarden`.`products_colours` (
  `colour_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  INDEX `colour_id` (`colour_id` ASC) VISIBLE,
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  CONSTRAINT `products_colours_colour_id_fk`
    FOREIGN KEY (`colour_id`)
    REFERENCES `dh_biogarden`.`colours` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `products_colours_product_id_fk`
    FOREIGN KEY (`product_id`)
    REFERENCES `dh_biogarden`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)



-- -----------------------------------------------------
-- Table `dh_biogarden`.`sizes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dh_biogarden`.`sizes` ;

CREATE TABLE IF NOT EXISTS `dh_biogarden`.`sizes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)



-- -----------------------------------------------------
-- Table `dh_biogarden`.`addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dh_biogarden`.`addresses` ;

CREATE TABLE IF NOT EXISTS `dh_biogarden`.`addresses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `street_name` VARCHAR(30) NOT NULL,
  `street_number` VARCHAR(10) NOT NULL,
  `city` VARCHAR(20) NOT NULL,
  `state` INT UNSIGNED NOT NULL,
  `zip_code` CHAR(4) NOT NULL,
  `other_info` VARCHAR(30) NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `addresses_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `dh_biogarden`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)



-- -----------------------------------------------------
-- Table `dh_biogarden`.`carts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dh_biogarden`.`carts` ;

CREATE TABLE IF NOT EXISTS `dh_biogarden`.`carts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `date_created` TIMESTAMP(3) NOT NULL,
  `total_amount` DECIMAL(5,2) UNSIGNED NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `carts_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `dh_biogarden`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)



-- -----------------------------------------------------
-- Table `dh_biogarden`.`carts_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dh_biogarden`.`carts_detail` ;

CREATE TABLE IF NOT EXISTS `dh_biogarden`.`carts_detail` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  `amount` DECIMAL(5,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) INVISIBLE,
  INDEX `cart_id` (`cart_id` ASC) INVISIBLE,
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  CONSTRAINT `cart_detail_cart_id_fk`
    FOREIGN KEY (`cart_id`)
    REFERENCES `dh_biogarden`.`carts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cart_detail_product_id_fk`
    FOREIGN KEY (`product_id`)
    REFERENCES `dh_biogarden`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)



-- -----------------------------------------------------
-- Table `dh_biogarden`.`products_sizes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dh_biogarden`.`products_sizes` ;

CREATE TABLE IF NOT EXISTS `dh_biogarden`.`products_sizes` (
  `size_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  INDEX `size_id` (`size_id` ASC) INVISIBLE,
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  CONSTRAINT `products_sizes_size_id_fk`
    FOREIGN KEY (`size_id`)
    REFERENCES `dh_biogarden`.`sizes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `products_sizes_product_id_fk`
    FOREIGN KEY (`product_id`)
    REFERENCES `dh_biogarden`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
